import { createSlice } from "@reduxjs/toolkit";

type accountDetailsState = {
  accountDetails: {
    accountId: number;
  };
};

const accountDetailsInfo = createSlice({
  name: "accountDetails",
  initialState: {
    accountId: 0,
  },
  reducers: {
    // Reducer function to set the file name
    setAccountId(state, action) {
      state.accountId = action.payload; // Update the file name
    },
  },
});

// Extract the action creators from courseSettingsInfo
export const { setAccountId } = accountDetailsInfo.actions;
// Export the reducer function generated by createSlice
export default accountDetailsInfo.reducer;
// Export the RootState type for typing the Redux store
export type { accountDetailsState };
