import { createSlice } from "@reduxjs/toolkit";

type trackerDetailsState = {
  trackerDetails: {
    trackerId: number;
    status: string;
  };
};

const trackerDetailsInfo = createSlice({
  name: "trackerDetails",
  initialState: {
    trackerId: "",
    status: "",
  },
  reducers: {
    // Reducer function to set the file name
    setTrackerId(state, action) {
      state.trackerId = action.payload; // Update the file name
    },
    setTrackerStatus(state, action) {
      state.status = action.payload; // Update the file name
    },
  },
});

// Extract the action creators from courseSettingsInfo
export const { setTrackerId, setTrackerStatus } = trackerDetailsInfo.actions;
// Export the reducer function generated by createSlice
export default trackerDetailsInfo.reducer;
// Export the RootState type for typing the Redux store
export type { trackerDetailsState };
