spring:
  application:
    name: GoalTracker
  datasource:
    url: jdbc:mysql://localhost:5432/your_database_name
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update # Automatically update the database schema (can be changed to 'validate', 'none', etc.)
    show-sql: true # Log SQL queries in the console
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

server:
  port: 8081
